-- Create leaderboards table
CREATE TABLE public.leaderboards (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "leagueId" integer NOT NULL,
    data jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT leaderboards_pkey PRIMARY KEY (id),
    CONSTRAINT leaderboards_leagueId_fkey FOREIGN KEY ("leagueId") REFERENCES public.leagues(id) ON DELETE CASCADE
);

-- Enable Row Level Security (RLS) if needed, or make it public read
ALTER TABLE public.leaderboards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.leaderboards
    FOR SELECT TO public USING (true);
