DROP EXTENSION pg_net;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE SEQUENCE public.event_id_seq AS integer;
CREATE SEQUENCE public.league_id_seq AS integer;
CREATE TABLE public.events (id integer DEFAULT nextval('public.event_id_seq'::regclass) NOT NULL, name character varying(100) NOT NULL, date character varying(50) NOT NULL, "startTime" character varying(50), "leagueId" integer NOT NULL, "ticketLink" character varying(255), "eventType" character varying(50), game character varying(20), description text, prizes text, "entryFee" character varying(50), "excludedDates" text);
ALTER SEQUENCE public.event_id_seq OWNED BY public.events.id;
GRANT ALL ON SEQUENCE public.event_id_seq TO anon;
GRANT ALL ON SEQUENCE public.event_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.event_id_seq TO service_role;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ADD CONSTRAINT event_pkey PRIMARY KEY (id);
GRANT ALL ON public.events TO anon;
GRANT ALL ON public.events TO authenticated;
GRANT ALL ON public.events TO service_role;
CREATE INDEX idx_event_league_id ON public.events ("leagueId");
CREATE TABLE public.leagues (id integer DEFAULT nextval('public.league_id_seq'::regclass) NOT NULL, name character varying(100) NOT NULL, logo character varying(255), website character varying(255), "socialLink" character varying(255), "eventLink" character varying(255), "brandColor" character varying(50), "webLink" character varying(255), location character varying(255), latitude double precision, longitude double precision, accessibility text, directions text);
ALTER SEQUENCE public.league_id_seq OWNED BY public.leagues.id;
GRANT ALL ON SEQUENCE public.league_id_seq TO anon;
GRANT ALL ON SEQUENCE public.league_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.league_id_seq TO service_role;
ALTER TABLE public.leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leagues ADD CONSTRAINT league_pkey PRIMARY KEY (id);
ALTER TABLE public.events ADD CONSTRAINT event_league_id_fkey FOREIGN KEY ("leagueId") REFERENCES public.leagues(id);
GRANT ALL ON public.leagues TO anon;
GRANT ALL ON public.leagues TO authenticated;
GRANT ALL ON public.leagues TO service_role;
CREATE TABLE public.weekly_events (id integer DEFAULT nextval('public.event_id_seq'::regclass) NOT NULL, name character varying(100) NOT NULL, date character varying(50) NOT NULL, "startTime" character varying(50), "leagueId" integer NOT NULL, "ticketLink" character varying(255), "eventType" character varying(50), game character varying(20), description text, prizes text, "entryFee" character varying(50), "excludedDates" text[] DEFAULT '{}'::text[]);
ALTER TABLE public.weekly_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_events ADD CONSTRAINT "weekly_events_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES public.leagues(id);
ALTER TABLE public.weekly_events ADD CONSTRAINT weekly_events_pkey PRIMARY KEY (id);
GRANT ALL ON public.weekly_events TO anon;
GRANT ALL ON public.weekly_events TO authenticated;
GRANT ALL ON public.weekly_events TO service_role;
CREATE INDEX weekly_events_league_id_idx ON public.weekly_events ("leagueId");
