-- Create welsh_players table to track verified Welsh player names
CREATE TABLE IF NOT EXISTS public.welsh_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

-- Seed with some initial verified Welsh players
INSERT INTO public.welsh_players (name) VALUES 
('Luke Enness'),
('Thomas Williams'),
('Dylan Jenkins'),
('Oliver Jones')
ON CONFLICT (name) DO NOTHING;
